### PR TITLE
doc: use custom MathJax package and config to display \longrightleftharpoons correctly

### PR DESCRIPTION
**Pull request by pjaap**
In a discussion with @Da-Be-Ru @jpthiele we developed a hack to display the broken math symbols in the current doc in https://j-fu.github.io/VoronoiFVM.jl/dev/plutostatichtml_examples/heterogeneous-catalysis/

`Pluto.jl` uses a different `MathJax` than `Documenter.jl`.
Especially, we need the LaTeX package `mhchem`.

The solution is not intended to be final. A good solution would require to extract the `MathJax` package from `Pluto.jl` and pass this to the `MathJax3` call as a `url` keyword.

### CODE REVIEW

**Comment by Da-Be-Ru** [comment]
I believe there are several ways to extract the `MathJax` source url used by the `Pluto.jl` transitive dependency in the `docs` environment. My understanding is that the only thing determining this is the [`editor.html` head in the `Pluto.jl` frontend](https://github.com/fonsp/Pluto.jl/blob/main/frontend/editor.html#L45) (the `not-the-src-yet` property is later copied into a `src` property by the invoked [`setup_mathjax`](https://github.com/fonsp/Pluto.jl/blob/main/frontend/common/SetupMathJax.js) function after an initial setup is done).

A straightfoward way to extract this URL from the `docs` environment is to extract the local `Pluto` source directory from the dependency graph and regex it out of there.

But since this is not an issue specific to `VoronoiFVM.jl`, I would actually suggest to escalate this functionality up to `ExampleJuggler.jl` which is where the `@docplutonotebooks` macro resides after all. Maybe this macro should already provide the proper `mathengine` to the `Documenter.HTML` call as well.

I already hacked together an example solution that could later be incorporated into `ExampleJuggler.jl`.
If you add me as a collaborator to your fork, @pjaap, I can demonstrate it with a commit.

**Comment by j-fu** [comment]
Checked locally - this works, great, thanks @pjaap .

@Da-Be-Ru : I think the PR is good enough in the moment.

ExampleJuggler has two ways of making Pluto notebooks accessible in the docs: rendered by Pluto itself in an iframe (using PlutoSliderServer.jl) or as plain HTML via PlutoStaticHTML.jl. 
Extracting the mathjax version pluto to me appears to be a bit too brittle anyway.

**Comment by Da-Be-Ru** [comment]
> ExampleJuggler has two ways of making Pluto notebooks accessible in the docs: rendered by Pluto itself in an iframe (using PlutoSliderServer.jl) or as plain HTML via PlutoStaticHTML.jl. Extracting the mathjax version pluto to me appears to be a bit too brittle anyway.

Maybe, but I think with hard-coded URLs, this current version could just lead to similar errors depending on whatever version of `Pluto` the environment will resolve to and where this particular version of `Pluto` will get its `MathJax` source files from.

I tried my hand at a rough demonstration of what I mean [on this fork](https://github.com/Da-Be-Ru/VoronoiFVM.jl/commit/d53887fb104de88fb6231d5fdb5cd4d6ad59bb10).

**Comment by j-fu** [comment]
Ok, we should keep this as is now and wait for https://github.com/JuliaDocs/Documenter.jl/pull/2549

**Comment by pjaap** [comment]
https://github.com/JuliaDocs/Documenter.jl/pull/2549 looks like a better solution than what we did downstream here. 
However, we still need to place the `mhchem` LaTeX package into the MathJax config. I wonder if there is a cleaner way than to overwrite the whole config.

**Comment by j-fu** [comment]
Just added this to the Documenter PR...

https://github.com/JuliaDocs/Documenter.jl/pull/2549/commits/c17b76297f4aab07ea8bcb235c6b1af7f3c1c340

**Pull request merged**
