### PR TITLE
export upgrade_grid_cellwise! for accessing nodefactors

### PR DESCRIPTION
**Pull request by dilaraabdel**
With upgrade_grid_cellwise! the user can access the nodefactors, which are needed to calculate the integral of a solution $u$.
We have

$$
\int_{\mathbf{\Omega}} u(\mathbf{x})   d\mathbf{x} = \sum_K \int_{\omega_K} u(\mathbf{x})  d\mathbf{x} \approx \sum_K |\omega_K| u(\mathbf{x}_K).
$$

The measure of the control volumes $|\omega_K|$ can be accessed with nodefactors

```julia
update_grid_cellwise!(sys, grid)
nodefac = sys.assembly_data.nodefactors
```

and the integral can be then calculated via

```julia
cellnodes = grid[CellNodes] # nodes per simplex x number of simplices
uInt = 0.0
for icell = 1:size(cellnodes, 2) # number of simplices
    for inode = 1:size(cellnodes, 1) # each node in simplex

        inodeIndexGrid = cellnodes[inode, icell]
        uInt = uInt + nodefac[inode, icell] * u[inodeIndexGrid] # u as the PDE solution

    end
end
```

### CODE REVIEW

**Comment by j-fu** [comment]
Hi, I am not sure if this is good as it exposes internals which I might want to be free to change. Also, I think it would lead to an inconsistent state for systems with edgewise assembly.

Instead I propose to add another method to `integrate`, see #116 . Let me know if this makes sense for you.

**Comment by dilaraabdel** [comment]
Hey @j-fu! I think, your method is unfortunately not working for me.
The function $n$ (density) I want to integrate depends on my FVM solution u (potential).
I want to calculate

```math
\frac{1}{| \mathbf{\Omega}|} \int_{\mathbf{\Omega}} n(u(\mathbf{x})) d\mathbf{x} \approx \frac{1}{| \mathbf{\Omega}|}  \sum_K | \omega_K| n( u(\mathbf{x}_K))
```
I tried to do the post processing with other numerical integration packages, but the problem is that they are mostly restricted to continuous representations of the arrays or rectangular domains.
Basically, I need access to 
- the area/volume of each control volume  $| \omega_K|$
- the area/volume of each region (as they may have non-planar edges)  $| \mathbf{\Omega}|$

Do you think, this is something we could put into ExtendableGrids? I am not sure, if we have access there to $| \omega_K|$ ... let me know what you think!

**Comment by j-fu** [comment]
But don't you have `n` (and `p`) in your storage term ?
In this case `integrate(sys,storage,solution)` should work.
This would give a matrix `nspecies x nregions` of integrals.

Also, there is a call `nodevolumess(system)` which gives the `\omega_k` (albeit not region-wise). For region-wise |\Omega_i| you could use `grid|CellVolumes|` from ExtendableGrids and  sum them region-wise.

Please have a look at the Postprocessing part of the docs and `vfvm_postprocess.jl` - we could add more methods there and also improve the documentation.

**Comment by dilaraabdel** [comment]
ahhh, you are completely right @j-fu ! Your suggestion fixed it! 
I will have a look at the docs and think about some suggestions, if necessary. Thank you very much :)

**Pull request merged**
